r"""Generate the production Docker artifacts without requiring Docker.

The official `langgraph dockerfile` / `langgraph build` commands work, but the
generated Dockerfile has three problems for *this* project:

1. On Windows the auth path is written with backslashes
   (`src\react_agent\auth.py`) because the CLI uses `Path.relative_to`. The
   file is then unreadable inside a Linux image, so authentication silently
   stops working.
2. Dependencies are installed with `uv pip install -e .` per package, which
   re-resolves the world against PyPI instead of using the locked versions the
   project was tested with.
3. `torch` from PyPI pulls the CUDA runtime (~4 GB) into a CPU-only
   deployment.

This script therefore regenerates the Dockerfile with the official generator
and applies those three patches, emits a lockfile-pinned requirements file, and
writes a docker-compose file built from the CLI's own `compose_as_dict()` so
Redis/Postgres/healthchecks stay exactly as LangGraph ships them.

Everything here runs offline and does not need a container runtime, which is
why it is also the checker used in CI (`--check`).

Usage:
    uv run python scripts/prepare_docker.py            # write artifacts
    uv run python scripts/prepare_docker.py --check    # verify they are current
"""

# Progress output is the intended deliverable of this CLI.
# ruff: noqa: T201

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCKER_DIR = REPO_ROOT / "docker"
DOCKERFILE = DOCKER_DIR / "Dockerfile"
COMPOSE_FILE = DOCKER_DIR / "docker-compose.yml"
LOCK_FILE = DOCKER_DIR / "requirements.lock.txt"

DEFAULT_TAG = "psychegraph:local"
DEFAULT_PORT = 8123
DEFAULT_BIND = "127.0.0.1"
BASE_IMAGE = "langchain/langgraph-api:3.11"
TORCH_CPU_INDEX = "https://download.pytorch.org/whl/cpu"

# Packages that only exist because PyPI's Linux torch wheel vendors CUDA. The
# deployment is CPU-only, so they are dropped from the image requirements.
CUDA_ONLY_PREFIXES = ("nvidia-", "cuda-", "triton")

DOCKERFILE_HEADER = """# Generated by scripts/prepare_docker.py - do not edit by hand.
# Source: `langgraph dockerfile` (langgraph-cli), patched with:
#   * forward-slash auth path (the CLI emits Windows backslashes)
#   * lockfile-pinned installs (docker/requirements.lock.txt)
#   * CPU-only torch from the PyTorch wheel index
# Regenerate with: uv run python scripts/prepare_docker.py
"""

COMPOSE_HEADER = """# Generated by scripts/prepare_docker.py - do not edit by hand.
# Redis, Postgres and the API healthcheck come from the LangGraph CLI's own
# composer (langgraph_cli.docker.compose_as_dict). Production-facing changes:
#   * the API is published on 127.0.0.1 only: the reverse proxy is the only
#     process that faces the internet (see deploy/Caddyfile.example)
#   * Postgres is NOT published to the host, so 5432 and 6379 stay on the
#     compose network (see docs/SECURITY_DEPLOYMENT.md, section 4)
#   * ../.env supplies secrets; psychegraph-hf (BGE-M3) and
#     ../data/vectorstore (Chroma) are the persistent state. Container paths
#     (RAG_VECTORSTORE_PATH, HF_HOME) are pinned in `environment` because
#     compose lets them win over ../.env.
# Requires Docker >= 25 / Compose v2.24+ (healthcheck start_interval, optional
# env_file path). Start with:
#   docker compose -f docker/docker-compose.yml --env-file .env up -d
# Local debugging with Postgres reachable on 5433:
#   docker compose -f docker/docker-compose.yml \\
#       -f deploy/docker-compose.debug.yml up -d
"""

INSTALL_BLOCK = f"""# -- Installing all local dependencies (lockfile-pinned) --
# The graph code is ADDed above; docker/requirements.lock.txt pins every
# third-party version that was tested, minus the CUDA-only packages.
RUN PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir \\
        --index-url {TORCH_CPU_INDEX} "torch==__TORCH_VERSION__"
RUN PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir \\
        -c /api/constraints.txt \\
        -r /deps/langgraph-fullstack-python/docker/requirements.lock.txt
RUN PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir --no-deps \\
        -e /deps/langgraph-fullstack-python
# -- End of local dependencies install --
"""

ENV_BLOCK = """ENV HF_HOME=/cache/huggingface
ENV HF_HUB_DISABLE_XET=1
ENV RAG_VECTORSTORE_PATH=/data/vectorstore
"""


def _log(message: str) -> None:
    print(message)


def export_requirements(uv_path: str) -> str:
    """Export the locked, platform-neutral dependency list.

    Args:
        uv_path: Path to the `uv` executable.

    Returns:
        The generated file body.
    """
    completed = subprocess.run(  # noqa: S603 - fixed argv, no shell
        [
            uv_path,
            "export",
            "--frozen",
            "--no-dev",
            "--no-emit-project",
            "--no-hashes",
            "--no-header",
            "--no-annotate",
        ],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    body: list[str] = []
    dropped: list[str] = []
    for line in completed.stdout.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        name = re.split(r"[=<>;\s]", stripped, maxsplit=1)[0].lower()
        if name.startswith(CUDA_ONLY_PREFIXES):
            dropped.append(name)
            continue
        body.append(stripped)
    if not any(line.startswith("torch==") for line in body):
        raise SystemExit("torch is missing from the exported requirements")
    _log(
        f"  requirements: {len(body)} pinned packages, {len(dropped)} CUDA-only dropped"
    )
    return (
        "# Generated by scripts/prepare_docker.py via:\n"
        "#   uv export --frozen --no-dev --no-emit-project --no-hashes\n"
        "# Installed into the image layer; the LangGraph runtime packages keep the\n"
        "# versions constrained by the base image (-c /api/constraints.txt).\n"
        "# CUDA-only packages (nvidia-*, cuda-*, triton) are omitted: the image\n"
        "# installs the CPU build of torch from download.pytorch.org/whl/cpu.\n"
        "\n" + "\n".join(body) + "\n"
    )


def generate_dockerfile_body() -> str:
    """Return the official, patched Dockerfile body.

    Returns:
        Dockerfile text.

    Raises:
        SystemExit: If the CLI output no longer matches the expected shape, so
            a silent divergence cannot ship.
    """
    from click.testing import CliRunner
    from langgraph_cli.cli import cli

    target = DOCKER_DIR / ".Dockerfile.generated"
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["dockerfile", str(target)],
        catch_exceptions=False,
    )
    if result.exit_code != 0:  # pragma: no cover - defensive
        _log(result.output)
        raise SystemExit("langgraph dockerfile failed")
    content = target.read_text(encoding="utf-8")
    target.unlink()
    for stray in DOCKER_DIR.glob(".dockerignore"):
        stray.unlink()
    return content


def patch_dockerfile(content: str, torch_version: str) -> str:
    """Apply the three documented patches to the generated Dockerfile.

    Args:
        content: Generated Dockerfile body.
        torch_version: Version pinned in the lock file.

    Returns:
        Patched Dockerfile body.

    Raises:
        SystemExit: If an expected marker is missing (CLI output changed).
    """
    if (
        "ADD . /deps/" not in content
        or "# -- Installing all local dependencies --" not in content
    ):
        raise SystemExit(
            "unexpected Dockerfile layout; update scripts/prepare_docker.py"
        )

    # Patch 1: the CLI writes `src\\react_agent\\auth.py` on Windows, which no
    # Linux container can import.
    windows_auth_path = r"src\\react_agent\\auth.py"  # JSON-escaped in the ENV value
    patched = content.replace(windows_auth_path, "src/react_agent/auth.py")
    auth_env = patched.split("ENV LANGGRAPH_AUTH=", 1)
    if (
        len(auth_env) != 2
        or "src/react_agent/auth.py" not in auth_env[1].split("\n", 1)[0]
    ):
        raise SystemExit("auth path patch did not apply")

    # Patch 2: lockfile-pinned dependency install instead of `uv pip install -e .`.
    start = patched.index("# -- Installing all local dependencies --")
    end = patched.index("# -- End of local dependencies install --")
    end += len("# -- End of local dependencies install --\n")
    patched = (
        patched[:start]
        + INSTALL_BLOCK.replace("__TORCH_VERSION__", torch_version)
        + patched[end:]
    )

    # Patch 3: cache/state locations that must live on volumes.
    env_anchor = "ENV LANGGRAPH_HTTP="
    if env_anchor not in patched:
        raise SystemExit("expected LANGGRAPH_HTTP env in the generated Dockerfile")
    patched = patched.replace(env_anchor, ENV_BLOCK + env_anchor, 1)

    if BASE_IMAGE not in patched:
        raise SystemExit("base image changed; update docs/DEPLOYMENT_OPTIONS.md")
    return DOCKERFILE_HEADER + "\n" + patched


def _unquoted(spec: str) -> str:
    r"""Strip the quotes the LangGraph CLI embeds in port mappings.

    The CLI formats compose dicts by hand (``ports: ["\"8123:8000\""]``), which
    round-trips through `yaml.safe_dump` as a scalar that *contains* quotes. A
    real `docker compose` run then sees `"8123:8000"` instead of `8123:8000`.

    Args:
        spec: Port mapping as the CLI produced it.

    Returns:
        The mapping without quote characters.
    """
    return spec.replace('"', "")


def build_compose(tag: str, port: int, bind: str) -> str:
    """Generate the compose file from the CLI's own composer.

    Args:
        tag: Image tag used for the `langgraph-api` service.
        port: Host port bound to the API container.
        bind: Host address the API port is published on. `127.0.0.1` keeps the
            Agent API off the internet; only a reverse proxy on the same host
            can reach it.

    Returns:
        YAML text (validated by re-parsing it).
    """
    import yaml
    from langgraph_cli.docker import DockerCapabilities, compose_as_dict

    capabilities = DockerCapabilities(
        version_docker=True,
        version_compose=True,
        healthcheck_start_interval=True,
        compose_type=True,
    )
    compose = compose_as_dict(capabilities, port=port, image=tag)
    services = compose["services"]
    api = services["langgraph-api"]
    api["ports"] = [f"{bind}:{port}:8000"]
    api["restart"] = "unless-stopped"
    api["env_file"] = [{"path": "../.env", "required": False}]
    # Compose gives `environment` precedence over `env_file`, and both override
    # the image ENV. The development `.env` points RAG_VECTORSTORE_PATH at a
    # relative path (fine on the host, wrong inside the container), so the
    # container values are pinned here instead of relying on the developer file.
    api["environment"] = {
        **api.get("environment", {}),
        "RAG_VECTORSTORE_PATH": "/data/vectorstore",
        "HF_HOME": "/cache/huggingface",
        "HF_HUB_DISABLE_XET": "1",
        # Passed through from ../.env or the shell. Empty means "no proxy", which
        # is what a normal VPS wants; on a workstation that can only reach the
        # internet through a local proxy (and where the container cannot use the
        # host's 127.0.0.1), set HTTP_PROXY/HTTPS_PROXY in .env instead of
        # editing this generated file.
        "HTTP_PROXY": "${HTTP_PROXY:-}",
        "HTTPS_PROXY": "${HTTPS_PROXY:-}",
        "NO_PROXY": "${NO_PROXY:-localhost,127.0.0.1,host.docker.internal}",
    }
    api["volumes"] = [
        "psychegraph-hf:/cache/huggingface",
        "../data/vectorstore:/data/vectorstore",
    ]
    # Postgres must not listen on the host in a public deployment: the compose
    # network is enough for the API, and deploy/docker-compose.debug.yml adds
    # the host mapping back for local debugging.
    services["langgraph-postgres"].pop("ports", None)
    for service in services.values():
        published = service.get("ports")
        if isinstance(published, list):
            service["ports"] = [_unquoted(entry) for entry in published]
    compose.setdefault("volumes", {})["psychegraph-hf"] = {"driver": "local"}

    text = COMPOSE_HEADER + yaml.safe_dump(compose, sort_keys=False, allow_unicode=True)
    parsed = yaml.safe_load(text)
    assert parsed["services"]["langgraph-api"]["ports"] == [f"{bind}:{port}:8000"]
    assert "ports" not in parsed["services"]["langgraph-postgres"]
    assert "ports" not in parsed["services"]["langgraph-redis"]
    return text


def uv_executable() -> str:
    """Locate the uv binary.

    Returns:
        Path to uv.

    Raises:
        SystemExit: If uv is not available.
    """
    found = shutil.which("uv")
    if found:
        return found
    candidates = list((Path.home() / "anaconda3" / "envs").glob("*/Scripts/uv.exe"))
    if candidates:
        return str(candidates[0])
    raise SystemExit("uv not found on PATH; pass --uv <path>")


def write_or_check(path: Path, content: str, check: bool) -> bool:
    """Write a file, or verify it already matches.

    Args:
        path: Target file.
        content: Expected content.
        check: When True, only compare.

    Returns:
        True when the file is current.
    """
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != content:
            _log(f"  STALE: {path.relative_to(REPO_ROOT)}")
            return False
        _log(f"  ok: {path.relative_to(REPO_ROOT)}")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    _log(f"  wrote: {path.relative_to(REPO_ROOT)}")
    return True


def main() -> int:
    """Generate (or verify) the Docker artifacts.

    Returns:
        Process exit code.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    parser.add_argument("--tag", default=DEFAULT_TAG, help="image tag to build")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT, help="host port")
    parser.add_argument(
        "--bind",
        default=DEFAULT_BIND,
        help="host address for the API port (default: loopback only)",
    )
    parser.add_argument("--uv", default=None, help="path to the uv executable")
    args = parser.parse_args()

    uv_path = args.uv or uv_executable()
    _log(f"prepare_docker: exporting locked requirements ({Path(uv_path).name})")
    requirements = export_requirements(uv_path)
    torch_version = next(
        line.split("==", 1)[1].split(";")[0].strip()
        for line in requirements.splitlines()
        if line.startswith("torch==")
    )

    _log("prepare_docker: generating Dockerfile via langgraph CLI")
    dockerfile = patch_dockerfile(generate_dockerfile_body(), torch_version)

    _log("prepare_docker: generating docker-compose.yml via langgraph CLI")
    compose = build_compose(args.tag, args.port, args.bind)

    ok = True
    for path, content in (
        (LOCK_FILE, requirements),
        (DOCKERFILE, dockerfile),
        (COMPOSE_FILE, compose),
    ):
        ok = write_or_check(path, content, args.check) and ok

    if not ok:
        _log("artifacts are stale; run: uv run python scripts/prepare_docker.py")
        return 1
    if not args.check:
        _log(
            "next steps (need a Docker host):\n"
            f"  docker build -f docker/Dockerfile -t {args.tag} .\n"
            f"  docker compose -f docker/docker-compose.yml --env-file .env up -d\n"
            f"  curl http://localhost:{args.port}/health"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
